# Generated by Django 5.2.10 on 2026-01-16 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmapnode',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='roadmapnode',
            name='xp',
            field=models.IntegerField(default=0),
        ),
    ]
